// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5qq5UkWIb_5JvKFhnwqZSQXRU1ljIGb8',
    appId: '1:616534217600:web:4f7b769e0de36d9a0a6765',
    messagingSenderId: '616534217600',
    projectId: 'chat-app-firebase-e78f4',
    authDomain: 'chat-app-firebase-e78f4.firebaseapp.com',
    storageBucket: 'chat-app-firebase-e78f4.appspot.com',
    measurementId: 'G-HF7PCSDF9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALtiNwQFA73oeli5YdE6ssu2S7hxfO1Og',
    appId: '1:616534217600:android:28462500f9c8ccd30a6765',
    messagingSenderId: '616534217600',
    projectId: 'chat-app-firebase-e78f4',
    storageBucket: 'chat-app-firebase-e78f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq7_RErnfPwDTDra4RJ_kxnG2pzDwRx6k',
    appId: '1:616534217600:ios:bbe13aee37cd67370a6765',
    messagingSenderId: '616534217600',
    projectId: 'chat-app-firebase-e78f4',
    storageBucket: 'chat-app-firebase-e78f4.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDq7_RErnfPwDTDra4RJ_kxnG2pzDwRx6k',
    appId: '1:616534217600:ios:edbfe383fb0910a30a6765',
    messagingSenderId: '616534217600',
    projectId: 'chat-app-firebase-e78f4',
    storageBucket: 'chat-app-firebase-e78f4.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
